### ISSUE TITLE
Does not work with 4.0.1

### ISSUE THREAD

**Issue by davidmontgom** [gevgeny/angular2-highcharts#180]
Failed to compile.

/Users/Documents/frontend/ang4test/src/app/app.module.ts (44,25): Cannot find name 'require'.

fails here --- ChartModule.forRoot(require('highcharts')),

**Comment by davidmontgom** [comment]
DUDES...so as to not waste other devs time...remove your repo or make explicit that you will not support angular4.

**Comment by emcpadden** [comment]
I haven't gone to Angular4 yet but plan to soon.  Was this issue closed because it really does work on Angular4 or is this something that is still pending.  Thanks very much for any info here. I really appreciate this module!!!  It has been very very helpful for us!  THANKS!!!!

**Comment by suuuunto** [comment]
Same problem here, is there a solution?

**Comment by suuuunto** [comment]
https://github.com/gevgeny/angular2-highcharts/issues/176
